<a href="https://colab.research.google.com/github/ashutoshsinha25/pytorch-development/blob/main/Fundamentals/01_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Link to resource notebook : [Pytorch-resource](https://www.learnpytorch.io/)

In [2]:
# importing the lib
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating a tensor

1. pytorch tensors are created using torch.tensor()

In [3]:
# scaler --> it has no dimensions
scaler = torch.tensor(7)
scaler

tensor(7)

In [8]:
print("Shape of the scaler tensor : ", scaler.ndim) # --> returns the dimension of tensor
print("Value of the scaler tensor : ", scaler.item()) # --> return the value of that tensor as a regular python integer (int)

Shape of the scaler tensor :  0
Value of the scaler tensor :  7


In [9]:
# vector # --> it has one dimensions
vector = torch.tensor([7,7])
vector

tensor([7, 7])

> `.item()` : This only works for tensors with one element. For other cases, see tolist().

In [15]:
print("Shape of the vector tensor : ", vector.ndim) # --> returns the dimension of tensor
print("Value of the vector tensor : ", vector.tolist())

Shape of the vector tensor :  1
Value of the vector tensor :  [7, 7]


In [ ]:
scaler.shape , vector.shape # shapes of values

(torch.Size([]), torch.Size([2]))

In [ ]:
# MATRIX # --> it has two dimensions
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim) # --> returns the dimension of tensor

2


In [ ]:
scaler.shape , vector.shape , MATRIX.shape # shapes of values

(torch.Size([]), torch.Size([2]), torch.Size([2, 2]))

In [ ]:
# TENSOR # --> it has three dimensions
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
print(TENSOR.ndim) # --> returns the dimension of tensor

3


In [ ]:
scaler.shape , vector.shape , MATRIX.shape , TENSOR.shape# shapes of values

(torch.Size([]), torch.Size([2]), torch.Size([2, 2]), torch.Size([1, 3, 3]))

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
TENSOR[0][1]

tensor([3, 4, 5])

### Random tensor


In [ ]:
# create a random tensor of size/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2827, 0.7133, 0.7868, 0.2077],
        [0.3019, 0.5308, 0.9402, 0.9068],
        [0.1330, 0.3965, 0.3025, 0.5206]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height, width , color channels (R,G,B)
# we can also have color channels, height , width as size values
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand((3,244,244)) # use this syntax : color,height,width ***********************************

tensor([[[0.6154, 0.7796, 0.9463,  ..., 0.0829, 0.0093, 0.6292],
         [0.1597, 0.9956, 0.5932,  ..., 0.0683, 0.5719, 0.4896],
         [0.1077, 0.5776, 0.5817,  ..., 0.0064, 0.4525, 0.5315],
         ...,
         [0.0426, 0.5295, 0.7270,  ..., 0.1428, 0.0172, 0.3726],
         [0.9048, 0.8624, 0.0415,  ..., 0.8647, 0.1060, 0.2111],
         [0.0426, 0.8774, 0.8886,  ..., 0.7658, 0.2806, 0.6786]],

        [[0.0670, 0.1158, 0.2727,  ..., 0.2687, 0.0108, 0.3460],
         [0.0526, 0.7358, 0.9289,  ..., 0.8876, 0.0396, 0.0868],
         [0.4012, 0.5249, 0.1298,  ..., 0.3082, 0.2483, 0.3812],
         ...,
         [0.5880, 0.7056, 0.9215,  ..., 0.0701, 0.4319, 0.3959],
         [0.4484, 0.9293, 0.1131,  ..., 0.1117, 0.5695, 0.1921],
         [0.3939, 0.3004, 0.7896,  ..., 0.7264, 0.3167, 0.3923]],

        [[0.0898, 0.4303, 0.6812,  ..., 0.7234, 0.4718, 0.6980],
         [0.4376, 0.0898, 0.3421,  ..., 0.3319, 0.5076, 0.6694],
         [0.9280, 0.1171, 0.8662,  ..., 0.8513, 0.0360, 0.

### Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# data type of variable
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# torch.range() is depricated so instead use arange()
values = torch.arange(start = 0, end = 1000 , step = 22)
values

tensor([  0,  22,  44,  66,  88, 110, 132, 154, 176, 198, 220, 242, 264, 286,
        308, 330, 352, 374, 396, 418, 440, 462, 484, 506, 528, 550, 572, 594,
        616, 638, 660, 682, 704, 726, 748, 770, 792, 814, 836, 858, 880, 902,
        924, 946, 968, 990])

In [ ]:
# tensors-like : say you had a particular shape of a tensor you want to replcate sonewhere else, but you
# didn't want to explicitly define what that share should be.
values.shape

torch.Size([46])

In [ ]:
# creating tensor-like i.e. returns an array with zero values with the same shape as array
values_like_zeros = torch.zeros_like(values)
values_like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
values_like_ones = torch.ones_like(values)
values_like_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensors data type


**Note**:
 tensor datatypes is one of the 3 big erros you'll run into with pytorch and deep learning
 1. tensor not right datatype
 2. tensor not right shape
 3. tensor not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype # default value in pytorch is float32 so even if we said dtype - None, it would come as dytpe = float32

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor_2 = float_32_tensor.type(torch.float16) # this is the other way to do the same as above
float_16_tensor_2

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#imp params -- these are the most important params when creating a tensor

tensor = torch.tensor([3.0,6.0,9.0],
                      dtype=None, # what datatype is tensor (eg float32, float16, etc)
                      device=None, # what device is your tensor on
                      requires_grad=False) # weather or not to track gradients with this tensor operations


In [ ]:
# mul of different dtypes --> this works
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# mul of int and float --> this works

int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# doing the above with long tensor --> this works
long_tensor = torch.tensor([3,6,9],dtype=torch.long)
long_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting informations from the tensors (attributes)

 1. tensor not right datatype - to get dtype from a tensor,can use `tensor.dtype`
 2. tensor not right shape - to get shape from a tensor, can use `tensor.shape`
 3. tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7342, 0.6086, 0.2848, 0.3543],
        [0.4123, 0.4035, 0.9302, 0.7620],
        [0.2332, 0.3601, 0.9563, 0.8845]])

In [ ]:
# getting details about the tensor
print(some_tensor)
print(f'datatype of tensor : {some_tensor.dtype}')
print(f'shape of tensor : {some_tensor.shape}')
print(f'device of tensor : {some_tensor.device}')

tensor([[0.7342, 0.6086, 0.2848, 0.3543],
        [0.4123, 0.4035, 0.9302, 0.7620],
        [0.2332, 0.3601, 0.9563, 0.8845]])
datatype of tensor : torch.float32
shape of tensor : torch.Size([3, 4])
device of tensor : cpu


### Manipulating Tensors ( tensors operations )


Tensor operations includes:
* Additions
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Additions
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# Substraction
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in built functions
# builtin multiplication
torch.mul(tensor , 10) # ---> multiply each tensor by 10

tensor([10, 20, 30])

In [ ]:
# builtin addition
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# builtin substraction
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [ ]:
# builtin matrix multiplication
torch.matmul(tensor, torch.tensor([10,10, 10] , dtype = tensor.dtype))

tensor(60)

In [16]:
??torch # --> for checking doc

Object `torch # --> for checking doc` not found.


### Matrix multiplication

Two main ways of performinng multiplication in neural network and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)


There are two main rules that performing matrix multiplication needs to satisfy :
1. The **inner dimension** must match :
* `(3,2) @ (3,2)` - won't work
* `(2,3) @ (3,2)` or `(3,2) @ (2,3)` - will work

> @ : used for matrix multiplication

2. The resulting matrix has the shape of the **outer dimension** :
* `(2,3) @ (3,2) --> shape : (2,2)`

In [ ]:
# element wise multiplicaiton
print(tensor , '*' , tensor)
print(f'equal : {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal : tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor , tensor)

tensor(14)

In [ ]:
# matmul by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
val

CPU times: user 273 µs, sys: 47 µs, total: 320 µs
Wall time: 329 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor , tensor)

CPU times: user 68 µs, sys: 11 µs, total: 79 µs
Wall time: 84.9 µs


tensor(14)

### One of the most common errors in the deep learning that is shape errors

In [ ]:
 # shapes for matrix multiplication
 tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
 tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])

In [ ]:
torch.mm(tensor_A , tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: ignored

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches axes ot dimension of a given tensor.

In [ ]:
tensor_B.T # -- >transposed tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_A , tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max , mean , sum etc ( tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100, 10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# find the mon

torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean
torch.mean(x) , x.mean()

RuntimeError: ignored

> see the following : https://pytorch.org/docs/stable/tensors.html#:~:text=64%2Dbit%20integer%20(signed)

In [ ]:
# find the mean - note torch.mena() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### Finding positional min and max

In [ ]:
# find the position in tensor that has minimum value  --> return the position of target tensor where minimum value occurs
x.argmin() , torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# find the position in tensor that has the max value with argmax
x.argmax() , torch.argmax(x)

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keeo the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
* squeeze - removes all `1` dimensinos form a tensor
* unsqueeze - adds a `1` dimension to a target tensor
* premute - return a view of the input with dimensions permuted(swapped) in a certain way.


In [20]:
# create a tensor
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [26]:
# add an extra dim.
# reshape has to be compatible with the opriginal shape
# x_reshaped = x.reshape(1, 7) # invalid total elements from the original vals
x_reshaped = x.reshape(1, 9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [25]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [27]:
# change the view
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [28]:
# changing z chnages x ( because a view of a tensor shares the same memory as the original tensor)

In [32]:
# stack tenors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.ndim

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 2)

In [44]:
# remove all single dim from the tensor
print("previous tensor : ", x_reshaped )
print("previous tensor shape : ", x_reshaped.shape)

# removing the extra dims
x_squeeze = x_reshaped.squeeze()
print("\nnew tensor : ", x_squeeze)
print("new tensor shape : ", x_squeeze.shape)

previous tensor :  tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous tensor shape :  torch.Size([1, 9])

new tensor :  tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
new tensor shape :  torch.Size([9])


In [48]:
# add a single dim to a target tensor at a specific dim ( dimension )
print("previous tensor : ", x_squeeze )
print("previous tensor shape : ", x_squeeze.shape)

# add an extra dims
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print("\nnew tensor : ", x_unsqueeze)
print("new tensor shape : ", x_unsqueeze.shape)

previous tensor :  tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
previous tensor shape :  torch.Size([9])

new tensor :  tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
new tensor shape :  torch.Size([1, 9])


In [50]:
 # rearrange the dim of a target tensor in a specified order
 x_original = torch.rand(size=(224,224,3)) # [ht, wt, channel]

# permute the original tensor to rearrange the axis (or dims) order
 x_permuted = x_original.permute(2, 0, 1) # shifts axis 0-> 1, 1-> 2, 2-> 0

 print("previous shape : ", x_original.shape)
 print("new shape : ", x_permuted.shape) # [channel, ht, wt]


previous shape :  torch.Size([224, 224, 3])
new shape :  torch.Size([3, 224, 224])


In [57]:
x_original[0,0,0] = 123456

In [59]:
x_permuted[0,0,0] # val was chaned in the both original and permuted when we change on place as permute is a view of the original tensor

tensor(123456.)

### Indexing (selecting data from tensor)



In [60]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
# index on the tensor; outer bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
# index on the middle backet (dim 1)
x[0][0]

tensor([1, 2, 3])

In [63]:
# index on the inner bracket (last dim )
x[0][0][0]

tensor(1)

In [65]:
# we can also use ":" to select "all " of the target dim
x[:,0 ]

tensor([[1, 2, 3]])

In [67]:
x[: , : , 1]

tensor([[2, 5, 8]])

In [68]:
x[:, 1, 1]

tensor([5])

In [69]:
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch tensor and Numpy


* data in numpy, we want in pytorch -> `torch.from_numpy(ndarray)`
* pytorch tensor to numpy -> `torch.tensor.numpy()`


default dtype of numpy : `float64`

default dtype for pytorch : `float32`

In [7]:
import torch
import numpy as np

# numpy array to tensor
arr=np.arange(1., 8.)
tensor = torch.from_numpy(arr) # when converting, pytroch reflects numpy dtypes passed (but good practice iss to check)
arr, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [8]:
arr.dtype

dtype('float64')

In [9]:
tensor.dtype

torch.float64

In [10]:
# changing the val of arr : this doesnot change the val of tensor
arr = arr + 2
arr, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
# tensor to numpy
tensor = torch.ones(7) # pytorch default dtype = float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [13]:
# changing the tensor
tensor = tensor + 1
numpy_tensor, tensor # they dont share memory

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

### Reproducibility (trying to take random out of random)

`random seed` : flavour the randomness

In [24]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [27]:
# make some randomm but reproducible tensors
#
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensor and pytorch obj on GPU's (making faster computation)

In [1]:
!nvidia-smi

Thu Jul 11 14:20:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [5]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# count number of device
torch.cuda.device_count()

1

###Putting tensors (and models ) on the GPU


In [9]:
# create tensor (default on CPU )
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
# if tensor is on GPU, we can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')